name: deploy-github-pages
on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: git setup
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
        env:
          user_name: 'github-acitons[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com' 
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: install dependencies
        run: npm install
      - name: build app
        run: npm run deploy
  deploy:
    needs: build
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: setup pages
        uses: actions/configure-pages@v3
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs"
      - name: deploy app to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1